name: Check changes of subscribed hashes
on:
  schedule:
    - cron: '*/7 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Check changes of subscribed hashes
        run: |
          curl --request GET \
          --url 'https://btc-look-up.vercel.app/api/v1/subscribe/checkChanges'
